apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: rattrapageintech2021  
  labels:
    app: mysq-server
    module: datacenter
    version: latest
spec:
  ports:
  - port: 3306
  selector:
    name: mysq-server
  type: ClusterIP
---
apiVersion: v1
kind: Deployment
metadata:
  name: k8s-mysql
  namespace: rattrapageintech2021  
  labels:
    server: mysq-server
    module: datacenter
    version: latest
spec:
  containers:
  - name: mysql
    image: mysql:latest
    resources:
      requests:
        memory: 128M    
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password
    ports:
    - name: mysql
      containerPort: 3306
      protocol: TCP
