apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: rattrapageintech2021
  labels:
    server: nginx-server
    module: webserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 80
      name: http
  selector:
    name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: rattrapageintech2021
spec:
  selector:
    matchLabels:
      server: nginx-server
  replicas: 3
  template:
    metadata:
      labels:
        server: nginx-server
        module: webserver
    spec:
      containers:
      - name: nginx-server
        image: nginx:stable-alpine
        resources:
         limits:
           cpu: 1
           memory: 128M
        ports:
        - containerPort: 80
        env:
        - name: alpha
          value: "rattrapageintech2021"
        - name: bravo
          value: "http"
        - name: charlie
          value: "nginx"
